version: '3.6'
networks:
  kbase-dev:
    name: kbase-dev
services:
  orcidlink:
    build:
      context: .
      dockerfile: Dockerfile
    image: kbase/orcidlink:dev
    container_name: ORCIDLink
    # We like to use the service module name here.
    hostname: ORCIDLink
    dns: 8.8.8.8
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/kb/module
    networks:
      - kbase-dev
    ports:
      - "5001:5000"
    environment:
      - DEV=yes
      - KBASE_ENDPOINT=${KBASE_ENDPOINT}
      - KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_ID=${KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_ID}
      - KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_SECRET=${KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_SECRET}
      - KBASE_SECURE_CONFIG_PARAM_MONGO_USERNAME=${KBASE_SECURE_CONFIG_PARAM_MONGO_USERNAME}
      - KBASE_SECURE_CONFIG_PARAM_MONGO_PASSWORD=${KBASE_SECURE_CONFIG_PARAM_MONGO_PASSWORD}
    depends_on:
      - mongo
      - mongo-express
  mongo:
    image: mongo
    restart: always
    networks:
      - kbase-dev
    volumes:
      - ./scripts/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    # TODO: add volume mount to preserve data between runs.
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_root
      MONGO_INITDB_ROOT_PASSWORD: dev_r00t
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - kbase-dev
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev_r00t
      ME_CONFIG_MONGODB_URL: mongodb://dev_root:dev_r00t@mongo:27017/
