version: '3.6'
networks:
  kbase-dev:
    name: kbase-dev
services:
  orcidlink:
    build:
      context: .
      dockerfile: Dockerfile
    image: kbase/orcidlink:dev
    container_name: ORCIDLink
    # We like to use the service module name here.
    hostname: ORCIDLink
    dns: 8.8.8.8
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/kb/module
    networks:
      - kbase-dev
    ports:
      - "5001:5000"
    environment:
      - DEV=${DEV:-}
      - KBASE_ENDPOINT=${KBASE_ENDPOINT}
      - ORCID_CLIENT_ID=FOO
      - ORCID_CLIENT_SECRET=BAR
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongo
    entrypoint:
      - bash
  mongo:
    image: mongo
    restart: always
    networks:
      - kbase-dev
    volumes:
      - ./scripts/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_root
      MONGO_INITDB_ROOT_PASSWORD: dev_r00t
