#
# A dockerfile which simulates production better than the main dockerfile, which is for development.
#
version: '3.6'
networks:
  kbase-dev:
    name: kbase-dev
services:
  orcidlink:
    build:
      context: .
      dockerfile: Dockerfile
    image: kbase/orcidlink:dev
    container_name: ORCIDLink
    hostname: ORCIDLink
    dns: 8.8.8.8
    networks:
      - kbase-dev
    ports:
      - "5001:5000"
    environment:
      - DEV=no
      - KBASE_ENDPOINT=${KBASE_ENDPOINT}
      - KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_ID=${KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_ID}
      - KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_SECRET=${KBASE_SECURE_CONFIG_PARAM_ORCID_CLIENT_SECRET}
      - KBASE_SECURE_CONFIG_PARAM_MONGO_USERNAME=${KBASE_SECURE_CONFIG_PARAM_MONGO_USERNAME}
      - KBASE_SECURE_CONFIG_PARAM_MONGO_PASSWORD=${KBASE_SECURE_CONFIG_PARAM_MONGO_PASSWORD}
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    networks:
      - kbase-dev
    volumes:
      - ./scripts/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_root
      MONGO_INITDB_ROOT_PASSWORD: dev_r00t