#
# A dockerfile which simulates production better than the main dockerfile, which is for development.
#
version: '3.6'
networks:
  kbase-dev:
    name: kbase-dev
services:
  orcidlink:
    build:
      context: .
      dockerfile: Dockerfile
    image: kbase/orcidlink:dev
    container_name: ORCIDLink
    hostname: ORCIDLink
    dns: 8.8.8.8
    networks:
      - kbase-dev
    ports:
      - "5001:5000"
    environment:
      - DEV=no
      - KBASE_ENDPOINT=${KBASE_ENDPOINT}
      - ORCID_API_BASE_URL=${ORCID_API_BASE_URL}
      - ORCID_OAUTH_BASE_URL=${ORCID_OAUTH_BASE_URL}
      - ORCID_CLIENT_ID=${ORCID_CLIENT_ID}
      - ORCID_CLIENT_SECRET=${ORCID_CLIENT_SECRET}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongo
    command: [ "scripts/run-server.sh" ]
  mongo:
    image: mongo:3.6.13
    restart: always
    networks:
      - kbase-dev
    volumes:
      - ./scripts/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_root
      MONGO_INITDB_ROOT_PASSWORD: dev_r00t