[tool.poetry]
name = "orcid-link"
version = "0.1.0"
description = ""
authors = ["Erik Pearson <eapearson@lbl.gov>"]

[tool.poetry.dependencies]
python = "3.11.1"
cache3 = "0.3.3"
dicttoxml2 = "2.1.0"
fastapi = "0.89.1"
httpx = "0.23.3"
jinja2-tools = "1.0.7"
pymongo = "4.3.3"
PyYAML = "6.0"
toml = "0.10.2"
types-toml = "0.10.8.2"
uvicorn = "0.20.0"
xmltodict = "0.13.0"


[tool.poetry.dev-dependencies]
mongomock = "4.1.2"
mypy = "1.0.0"
pyfakefs = "5.1.0"
pytest = "7.2.1"
pytest-cov = "4.0.0"
types-python-dateutil = "2.8.19.6"
types-PyYAML = "6.0.12.4"

[tool.poetry.group.dev.dependencies]
black = "22.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

