[tool.poetry]
name = "orcid-link"
version = "0.3.0"
description = ""
authors = ["Erik Pearson <eapearson@lbl.gov>"]

[tool.poetry.dependencies]
aiohttp = "3.8.4"
python = "3.11.4"
cachetools = "5.3.1"
dicttoxml2 = "2.1.0"
# email-validator = "1.3.1"
email-validator = "2.0.0.post2"
fastapi = "0.100.0"
httpx = "0.24.1"
jinja2-tools = "1.0.7"
pymongo = "4.4.0"
PyYAML = "6.0.1"
toml = "0.10.2"
uvicorn = "0.22.0"
uvloop = "0.17.0"
xmltodict = "0.13.0"

[tool.poetry.group.dev.dependencies]
black = "23.7.0"
mongomock = "4.1.2"
mypy = "1.4.1"
pipdeptree = "2.9.5"
pyfakefs = "5.2.3"
pytest = "7.4.0"
pytest-asyncio = "0.21.1"
pytest-cov = "4.1.0"
types-cachetools = "5.3.0.5"
types-python-dateutil = "2.8.19.13"
types-PyYAML = "6.0.12.10"
types-toml = "0.10.8.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
