[tool.poetry]
name = "orcid-link"
version = "0.1.0"
description = ""
authors = ["Erik Pearson <eapearson@lbl.gov>"]

[tool.poetry.dependencies]
python = "3.11.2"
cachetools = "5.3.0"
dicttoxml2 = "2.1.0"
email-validator = "1.3.1"
fastapi = "0.95.0"
httpx = "0.23.3"
jinja2-tools = "1.0.7"
pymongo = "4.3.3"
PyYAML = "6.0"
toml = "0.10.2"
uvicorn = "0.21.1"
xmltodict = "0.13.0"

[tool.poetry.group.dev.dependencies]
black = "23.1.0"
mongomock = "4.1.2"
mypy = "1.1.1"
pipdeptree = "2.6.0"
pyfakefs = "5.1.0"
pytest = "7.2.2"
pytest-cov = "4.0.0"
types-cachetools = "5.3.0.4"
types-python-dateutil = "2.8.19.10"
types-PyYAML = "6.0.12.8"
types-toml = "0.10.8.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

