#
# A dockerfile for running the server under development.
#
version: '3.6'
networks:
  kbase-dev:
    name: kbase-dev
services:
  orcidlink:
    build:
      context: .
    container_name: orcidlink
    hostname: orcidlink
    dns: 8.8.8.8
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/kb/module
    networks:
      # kbase-dev network enables it to be integrated into the kbase-ui proxy
      # for local ui integration work
      - kbase-dev
    ports:
      # NB cannot use 5000 because macOS uses it; it is handy to expose
      # this port for poking at the API during development.
      - "5003:5000"
    environment:
      - KBASE_ENDPOINT
      - ORCID_API_BASE_URL
      - ORCID_OAUTH_BASE_URL
      - ORCID_SITE_BASE_URL
      - ORCID_CLIENT_ID
      - ORCID_CLIENT_SECRET
      - MONGO_HOST
      - MONGO_PORT
      - MONGO_DATABASE
      - MONGO_USERNAME
      - MONGO_PASSWORD
    depends_on:
      - mongo
    command: [ 'scripts/start-server-dev.sh' ]
  mongo:
    # image: mongo:3.6.13
    image: mongo:6.0.7
    restart: always
    networks:
      - kbase-dev
    volumes:
      - ./tools/scripts/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    # TODO: add volume mount to preserve data between runs.
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_root
      MONGO_INITDB_ROOT_PASSWORD: dev_r00t
