---
name: Build Image without pushing
on:
  workflow_call:
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v3

      # At build time, we capture information about the
      # environment.

      # git-info creates a file git_info.toml in config
      - name: Get git info
        run: ./Taskfile git-info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build without push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: false
