---
name: Code checks and tests
on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
  release:
    branches:
      - main
    types:
      - published
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v3

      - name: Run type checks via mypy
        run: ./Taskfile mypy

      - name: Run "black" to ensure is formatted correctly
        run: ./Taskfile black

      - name: Generate openapi.json and compare to stored one
        run: ./Taskfile check-openapi

      - name: Run all tests
        run: ./Taskfile test
